# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2024.2.0-46-g9a13c1a
_src_path: gh:blakeNaccarato/copier-python
actions_runner: ubuntu-24.04
github_repo_name: boilerdaq
package_name: boilerdaq
project_description: Data acquisition for a nucleate pool boiling experimental apparatus
project_email: blake.naccarato@gmail.com
project_name: boilerdaq
project_owner_github_username: softboiler
project_owner_name: Blake Naccarato
project_version: 2024.1.2
python_version: '3.11'
year_of_project_creation: 2023
