# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2024.1.1-22-g4c3d14c
_src_path: gh:blakeNaccarato/copier-python
actions_runner: ubuntu-22.04
active: true
github_repo_name: boilerdaq
project_description: Data processing pipeline for a nucleate pool boiling apparatus.
project_email: blake.naccarato@gmail.com
project_name: boilerdaq
project_owner_github_username: softboiler
project_owner_name: Blake Naccarato
project_version: 0.4.0
python_version: '3.11'
year_of_project_creation: 2023
