exclude: |
  (?x)^(
    \.copier-answers\.yml
    |changelog/towncrier_template\.md\.jinja
  )$
ci:
  skip:
    - "sync"
    - "fawltydeps"
    - "fawltydeps-dev"
    - "pytest-fast-only"
  autoupdate_schedule: "quarterly"
default_install_hook_types:
  - "pre-commit"
  - "post-checkout" # sync
repos:
  - repo: "meta"
    hooks:
      # ? Enable this to ensure each hook runs against at least one file
      # - id: "check-hooks-apply"
      - id: "check-useless-excludes"
  - repo: "local"
    hooks:
      - id: "sync"
        name: "sync"
        stages:
          - "pre-commit"
          - "post-checkout"
        pass_filenames: false
        language: "system"
        entry: |
          pwsh -Command "./j.ps1 uv-sync"
      - id: "fawltydeps"
        name: "fawltydeps"
        pass_filenames: false
        language: "system"
        entry: "pwsh -NonInteractive -NoProfile -Command './j.ps1 fawltydeps'"
        files: |
          (?x)^(
            src/.*
            |pyproject\.toml
          )$
      - id: "fawltydeps-dev"
        name: "fawltydeps-dev"
        pass_filenames: false
        language: "system"
        entry: "pwsh -NonInteractive -NoProfile -Command './j.ps1 fawltydeps --config-file packages/_dev/pyproject.toml'"
        files: |
          (?x)^(
            packages/_dev/.*
            |docs/.*
            |tests/.*
          )$
      - id: "pytest-fast-only"
        name: "pytest-fast-only"
        pass_filenames: false
        language: "system"
        entry: 'pwsh -NonInteractive -NoProfile -Command ''./j.ps1 pytest -m `"not slow`"'''
        files: |
          (?x)^(
            .*/pyproject\.toml
            |docs/.*
            |requirements/.*
            |scripts/.*
            |src/.*
            |tests/.*
          )$
      - id: "synchronize-params"
        name: "synchronize-params"
        language: "system"
        entry: "pwsh -Command python -m boilerdaq.models.params"
        files: |
          (?x)^(
            src/boilerdaq/models/.*
            |params.yaml
          )$
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v5.0.0"
    hooks:
      - id: "check-illegal-windows-names"
      - id: "check-merge-conflict"
      - id: "destroyed-symlinks"
      - id: "detect-private-key"
      - id: "end-of-file-fixer"
      - id: "mixed-line-ending"
      - id: "trailing-whitespace"
        args: [--markdown-linebreak-ext=md]
      - id: "trailing-whitespace"
  - repo: "https://github.com/iterative/dvc"
    rev: "3.51.2"
    hooks:
      - id: "dvc-post-checkout"
        additional_dependencies: ["dvc[gs]"]
      - id: "dvc-pre-push"
        additional_dependencies: ["dvc[gs]"]
  - repo: "https://github.com/DavidAnson/markdownlint-cli2"
    rev: "v0.13.0"
    hooks:
      - id: "markdownlint-cli2"
  - repo: "https://github.com/srstevenson/nb-clean"
    rev: "3.3.0"
    hooks:
      - id: "nb-clean"
        args:
          - "--remove-empty-cells"
          - "--preserve-notebook-metadata"
          - "--preserve-cell-metadata"
          - "tags"
          - "--"
        files: |
          (?x)^(
            docs/.*
            |notebooks/.*
            |src/.*
            |tests/.*
          )$
  - repo: "https://github.com/rbubley/mirrors-prettier"
    rev: "v3.5.1"
    hooks:
      - id: prettier
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
  - repo: "https://github.com/charliermarsh/ruff-pre-commit"
    rev: "v0.9.3"
    hooks:
      - id: "ruff"
        args: ["--extend-fixable", "PIE790"]
        types_or: ["python", "pyi", "jupyter"]
      - id: "ruff-format"
        types_or: ["python", "pyi", "jupyter"]
