version: "1"

ignore:
  # The defaults
  - ".git"
  - "venv"
  - ".venv"
  - "env"
  - ".env"
  - ".tox"
  - "node_modules"
  - "vendor"
  # Extras
  - ".*"
  # Project-specific
  - "src/boilerdaq/shim.py"

rule_settings:
  python_version: "3.11"
  enable: ["default"]
